import { z } from "zod";

/**
 * Shared field primitives.
 *
 * Keeping these in one place means an id is validated the same way on every
 * entity, and a timestamp means the same thing everywhere.
 */

/** Internal primary key. UUIDv4, generated by the database on insert. */
export const uuidSchema = z.uuid();
export type Uuid = z.infer<typeof uuidSchema>;

/**
 * UTC instant, serialised as ISO-8601.
 *
 * Storage is `timestamptz`; the wire format is always a string so domain
 * objects stay JSON-serialisable across the server/client boundary.
 */
export const timestampSchema = z.iso.datetime({ offset: true });
export type Timestamp = z.infer<typeof timestampSchema>;

/** URL-safe identifier, unique per organization (or globally for orgs). */
export const slugSchema = z
  .string()
  .min(2)
  .max(64)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase words separated by hyphens");

/** ISO 3166-1 alpha-2, uppercased. */
export const countryCodeSchema = z
  .string()
  .length(2)
  .regex(/^[A-Z]{2}$/, "Use a two-letter uppercase country code");

/** IANA time zone name, e.g. "America/New_York". */
export const timezoneSchema = z.string().min(3).max(64);

/** BCP-47 language tag, e.g. "en-US". */
export const languageTagSchema = z.string().min(2).max(16);

/** Normalised 0–1 score used for relevance, engagement, and confidence. */
export const unitScoreSchema = z.number().min(0).max(1);

/**
 * Arbitrary structured data — raw platform payloads, rule conditions, audit
 * metadata. Recursive rather than `unknown` so it is provably serialisable.
 */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

export const jsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.null(),
    z.array(jsonValueSchema),
    z.record(z.string(), jsonValueSchema),
  ]),
);

export const jsonObjectSchema = z.record(z.string(), jsonValueSchema);
export type JsonObject = z.infer<typeof jsonObjectSchema>;

/** Every table carries these. */
export const timestampsSchema = z.object({
  createdAt: timestampSchema,
  updatedAt: timestampSchema,
});

/**
 * Ties a record to its tenant. Present on every business entity — rule 1 of the
 * architecture: every business record belongs to an organization.
 */
export const organizationOwnedSchema = z.object({
  id: uuidSchema,
  organizationId: uuidSchema,
});
