import {
  ANNUAL_MONTHS_BILLED,
  LISTED_LOCATION_LIMIT,
  LOWEST_LISTED_MONTHLY,
  MONTHS_CHARGED,
  PRICING_BANDS,
  type BillingPeriod,
  type PricingBand,
} from "@/lib/pricing/schedule";
import type { BillingInterval } from "@/domain";

/**
 * Lia's Stripe catalog, derived from the published rate card.
 *
 * Nothing in this module is typed by hand. Every tier, every amount, and the
 * self-service ceiling come from `@/lib/pricing/schedule` — the same module the
 * marketing page renders — so the price a customer reads and the price Stripe
 * charges cannot become two numbers. `tests/billing-catalog.test.ts` proves it
 * for every group size the schedule lists, which is the assertion that makes
 * generating the catalog from code worth the indirection.
 *
 * ## Why graduated, and why one price per interval
 *
 * The published schedule is graduated — "the way tax brackets work", as the
 * pricing page puts it — so an eleventh location does not reprice the ten
 * below it. Stripe models that directly with `billing_scheme: "tiered"` and
 * `tiers_mode: "graduated"`, which means one price covers every group size and
 * the quantity is simply the number of locations.
 *
 * The alternative — a flat per-unit price per band — would force a *price
 * change* every time a group crossed a boundary: a proration, a new price id
 * on the subscription, and a billing event the customer did not ask for,
 * triggered by adding a restaurant. One tiered price has none of that.
 *
 * ## The tier Lia can never reach
 *
 * Stripe requires the last tier of a tiered price to be unbounded (`up_to:
 * "inf"`). Lia's schedule is not unbounded: above `LISTED_LOCATION_LIMIT` the
 * price is quoted, not listed. Those two facts cannot both be expressed in one
 * price, so the catalog closes with an `inf` tier at the lowest listed rate
 * and **Lia refuses to sell into it** — at the Checkout action, at the
 * capacity action, at the `purchased_location_quantity` check constraint, and
 * at the capacity trigger on `locations`.
 *
 * That is not a workaround; it is where the enforcement belongs. Stripe's job
 * is to price a quantity, and it will price any quantity correctly. Deciding
 * that a hundred-and-first location is a conversation rather than a
 * transaction is a commercial rule, and commercial rules live in Lia.
 */

/**
 * Stable lookup keys, not price ids.
 *
 * Price ids differ between sandbox and live and are generated by Stripe, so a
 * price id in code or in an environment variable is a value somebody has to
 * copy correctly twice. A lookup key is chosen by Lia, identical in both
 * modes, and resolved at runtime — a typo becomes a startup-time failure
 * naming the missing key rather than a subscription created against the wrong
 * price.
 *
 * Versioned suffixes because a Stripe price is immutable once a subscription
 * uses it. Changing the rate card means creating `_v2` and moving the lookup
 * key across; existing subscribers keep the price they agreed to, which is the
 * behaviour anyone would expect and the reason the version is in the key.
 */
export const PRICE_LOOKUP_KEYS = {
  monthly: "lia_location_monthly_v1",
  annual: "lia_location_annual_v1",
} as const satisfies Record<BillingPeriod, string>;

/** The product every price hangs off. One product: Lia is one thing. */
export const PRODUCT_LOOKUP_KEY = "lia_reputation";

/** The most locations a customer may buy without talking to somebody. */
export const MAX_SELF_SERVICE_LOCATIONS = LISTED_LOCATION_LIMIT;

/** Stripe's word for the interval, from Lia's. */
export const STRIPE_INTERVAL: Record<BillingPeriod, BillingInterval> = {
  monthly: "month",
  annual: "year",
};

/** Lia's word for the interval, from Stripe's. */
export const BILLING_PERIOD: Record<BillingInterval, BillingPeriod> = {
  month: "monthly",
  year: "annual",
};

/**
 * One tier as Stripe's API expects it.
 *
 * `upTo` is `"inf"` on the last tier and a whole number everywhere else;
 * `unitAmount` is in the smallest currency unit, which for USD is cents.
 */
export interface CatalogTier {
  upTo: number | "inf";
  unitAmount: number;
}

/** Whole dollars to cents. Stripe deals only in the smallest unit. */
function cents(dollars: number): number {
  return Math.round(dollars * 100);
}

/**
 * What one location in this band costs for one billing period, in cents.
 *
 * The annual rate is the monthly rate times `ANNUAL_MONTHS_BILLED` — ten
 * months for a year — which is the single place the annual discount is
 * expressed. Because every band rate is a whole number of dollars and the
 * multiplier is a whole number, this is always an exact number of cents;
 * there is no rounding anywhere in the catalog, and therefore no cent that
 * can differ between the page's arithmetic and Stripe's.
 */
function bandAmount(band: PricingBand, period: BillingPeriod): number {
  const monthly = band.monthly ?? LOWEST_LISTED_MONTHLY;
  return cents(monthly * MONTHS_CHARGED[period]);
}

/**
 * The tier table for one interval.
 *
 * Reads straight off `PRICING_BANDS`, so adding or moving a band changes the
 * page and the catalog together. The quoted top band has no listed rate, so it
 * supplies the mandatory unbounded tier at the lowest listed rate — see the
 * module comment for why nothing can ever be sold into it.
 */
export function tiersFor(period: BillingPeriod): CatalogTier[] {
  return PRICING_BANDS.map((band) => ({
    upTo: band.to === null ? ("inf" as const) : band.to,
    unitAmount: bandAmount(band, period),
  }));
}

/**
 * What Stripe will charge for `quantity` locations, in cents.
 *
 * A local reimplementation of Stripe's graduated arithmetic, and it exists for
 * exactly one reason: so a test can assert that Stripe's tier table, walked
 * the way Stripe walks it, produces the same figure as the marketing page's
 * `monthlyTotal`/`annualTotal`. Two independent implementations agreeing on
 * every group size from 1 to 100 is a much stronger claim than one
 * implementation agreeing with itself.
 *
 * It is also what the billing screens quote before a customer confirms, so the
 * figure on the confirmation and the figure on the invoice come from the same
 * walk of the same tiers.
 */
export function chargeInCents(period: BillingPeriod, quantity: number): number {
  if (!Number.isInteger(quantity) || quantity < 1) {
    throw new Error(`chargeInCents: ${quantity} is not a whole number of locations`);
  }

  let remaining = quantity;
  let previousCeiling = 0;
  let total = 0;

  for (const tier of tiersFor(period)) {
    if (remaining <= 0) break;
    const ceiling = tier.upTo === "inf" ? quantity : tier.upTo;
    const unitsInTier = Math.min(remaining, ceiling - previousCeiling);
    if (unitsInTier > 0) {
      total += unitsInTier * tier.unitAmount;
      remaining -= unitsInTier;
    }
    previousCeiling = ceiling;
  }

  return total;
}

/**
 * Whether a location count can be sold without a conversation.
 *
 * The server asks this before creating a Checkout Session and before changing
 * capacity. It is deliberately a predicate over a number rather than a
 * validation of a form field, because the same rule has to hold for a quantity
 * that arrived from a form, from a reconciliation, and from a capacity change.
 */
export function isSelfServiceQuantity(quantity: number): boolean {
  return (
    Number.isInteger(quantity) &&
    quantity >= 1 &&
    quantity <= MAX_SELF_SERVICE_LOCATIONS
  );
}

/**
 * The date the first charge lands, given a trial that starts now.
 *
 * Exported rather than inlined into a component because it is quoted to the
 * customer before they hand over a card, and a figure a customer is shown
 * before paying should be computed somewhere a test can reach.
 */
export function firstChargeDate(trialStart: Date, trialDays: number): Date {
  const end = new Date(trialStart.getTime());
  end.setUTCDate(end.getUTCDate() + trialDays);
  return end;
}

/** Cents to the string a person reads: `$1,080`, or `$1,080.50` if it ever has cents. */
export function formatCents(amount: number): string {
  const dollars = amount / 100;
  const whole = Number.isInteger(dollars);
  return `$${dollars.toLocaleString("en-US", {
    minimumFractionDigits: whole ? 0 : 2,
    maximumFractionDigits: whole ? 0 : 2,
  })}`;
}

/** Named for the catalog script's output and the runbook's verification step. */
export const ANNUAL_MONTHS_BILLED_FOR_CATALOG = ANNUAL_MONTHS_BILLED;
