-- Restate the audit vocabulary so the check constraint matches AUDIT_EVENT_TYPES.
--
-- Generated by `npm run audit:vocabulary:generate` from `AUDIT_EVENT_TYPES` in
-- `src/domain/enums.ts`. Do not hand-edit: the value of this file is that its
-- list is derived rather than copied, and an edit here is exactly the stale
-- copy the generator exists to rule out. Add the event to the TypeScript array
-- and regenerate.
--
-- Postgres cannot extend a check constraint, so this restates the whole list.
-- `tests/audit-vocabulary-migrations.test.ts` replays every migration in
-- filename order and compares the final permitted set against that same array
-- in both directions, which is what fails if a later branch drops these names.

alter table public.audit_events
  drop constraint audit_events_known_event_type;

alter table public.audit_events
  add constraint audit_events_known_event_type check (
    event_type in (
      'mention.status_changed',
      'response.assigned',
      'response.approved',
      'response.rejected',
      'response.generated',
      'response.changes_requested',
      'response.edited',
      'escalation.assigned',
      'escalation.status_changed',
      'automation_rule.enabled',
      'automation_rule.disabled',
      'automation_rule.created',
      'automation_rule.updated',
      'automation_rule.duplicated',
      'automation_rule.archived',
      'automation_rule.simulated',
      'automation_rule.activation_refused',
      'automation_rule.executed',
      'automation_rule.execution_failed',
      'automation_sweep.completed',
      'location.manager_changed',
      'location.created',
      'location.updated',
      'location.status_changed',
      'integration.oauth_started',
      'integration.oauth_completed',
      'integration.connected',
      'integration.reauthorization_started',
      'integration.reauthorized',
      'integration.health_checked',
      'integration.health_degraded',
      'integration.profile_connected',
      'integration.profile_mapped',
      'location.created_from_integration',
      'integration.disconnected',
      'integration.credentials_revoked',
      'integration.credentials_revocation_failed',
      'integration.reviews_synced',
      'integration.review_sync_failed',
      'mention.analyzed',
      'mention.analysis_failed',
      'escalation.created_from_analysis',
      'organization.created',
      'membership.invited',
      'membership.invitation_revoked',
      'membership.joined',
      'membership.role_changed',
      'membership.status_changed',
      'membership.removed',
      'brand_voice.updated',
      'monitoring_query.polled',
      'monitoring_query.poll_failed',
      'monitoring_query.created',
      'monitoring_query.updated',
      'monitoring_query.deleted',
      'onboarding.started',
      'onboarding.organization_completed',
      'onboarding.source_connected',
      'onboarding.source_skipped',
      'onboarding.locations_completed',
      'onboarding.locations_skipped',
      'onboarding.brand_voice_completed',
      'onboarding.team_completed',
      'onboarding.team_skipped',
      'onboarding.completed',
      'onboarding.ready_viewed',
      'integration.listing_checked',
      'integration.listing_check_failed',
      'yelp_activity.detected',
      'mention.captured_manually',
      'response.publication_confirmed',
      'response.publication_unconfirmed',
      'reddit_monitor.created',
      'reddit_monitor.updated',
      'reddit_monitor.deleted',
      'reddit_monitor.polled',
      'reddit_monitor.poll_failed',
      'reddit_community.decision_recorded',
      'reddit_community.review_required',
      'reddit_content.removed',
      'reddit_content.reconciled',
      'response.published',
      'response.publish_failed',
      'response.publish_reconciled',
      'response.retracted',
      'review_widget.created',
      'review_widget.updated',
      'review_widget.disabled',
      'review_widget.enabled',
      'review_widget.embed_id_rotated',
      'press_widget.created',
      'press_widget.updated',
      'press_widget.disabled',
      'press_widget.enabled',
      'press_widget.embed_id_rotated'
    )
  );

comment on constraint audit_events_known_event_type on public.audit_events is
  'Closed list of audit event names, generated from AUDIT_EVENT_TYPES by npm run audit:vocabulary:generate. Every migration that adds one restates the whole list, because Postgres cannot extend a check constraint — tests/audit-vocabulary-migrations.test.ts pins this against AUDIT_EVENT_TYPES in both directions so a redefinition assembled from a stale copy cannot silently drop an event the application still emits.';

-- No entity-type change. `audit_entity_type` is a Postgres enum and its values
-- are added with `add value if not exists`, which is additive — unlike the
-- check constraint above, a later migration cannot drop an earlier one's value.
-- Add one in its own migration when a new subject appears.
