-- Lia foundation schema.
--
-- Every business table carries organization_id and is protected by row-level
-- security in migration 20260801000200. Timestamps are timestamptz and stored
-- in UTC. Primary keys are UUIDv4 generated by the database.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enum types
--
-- These mirror src/domain/enums.ts exactly. Changing one without the other is
-- the most likely way this schema drifts, so keep the two edits together.
-- ---------------------------------------------------------------------------

create type membership_role as enum (
  'owner', 'admin', 'communications_lead', 'location_manager',
  'approver', 'analyst', 'viewer'
);
create type membership_status as enum ('invited', 'active', 'suspended');

create type location_status as enum ('setup', 'active', 'review', 'inactive');

create type platform as enum (
  'google_business_profile', 'yelp', 'reddit', 'news_media', 'disqus',
  'trustpilot', 'tripadvisor', 'facebook', 'instagram'
);
create type platform_connection_status as enum (
  'pending', 'connected', 'action_required', 'disconnected', 'error'
);
create type platform_profile_status as enum (
  'pending', 'active', 'action_required', 'disconnected'
);

create type mention_source_type as enum (
  'google_review', 'yelp_review', 'trustpilot_review', 'tripadvisor_review',
  'reddit_post', 'reddit_comment', 'news_article', 'article_comment',
  'facebook_comment', 'instagram_comment'
);
create type mention_status as enum (
  'new', 'analyzed', 'draft_ready', 'needs_approval', 'escalated',
  'responded', 'monitoring', 'no_action_recommended', 'dismissed'
);
create type sentiment as enum ('positive', 'neutral', 'negative', 'mixed', 'unknown');
create type risk_level as enum ('low', 'medium', 'high', 'critical');

create type recommended_action as enum (
  'respond_publicly', 'respond_privately', 'contact_journalist',
  'publish_owned_statement', 'monitor', 'escalate', 'do_not_engage', 'dismiss'
);

create type response_draft_status as enum (
  'draft', 'awaiting_approval', 'approved', 'publishing', 'submitted',
  'published', 'rejected_by_platform', 'failed', 'deleted', 'dismissed'
);
create type response_type as enum (
  'public_reply', 'private_reply', 'journalist_email', 'article_comment',
  'social_statement', 'internal_briefing'
);
create type generated_by as enum ('ai', 'user', 'imported');

create type approval_status as enum ('pending', 'approved', 'rejected', 'canceled');

create type escalation_category as enum (
  'food_safety', 'injury', 'discrimination', 'employee_misconduct',
  'legal_threat', 'privacy', 'refund_dispute', 'media_inquiry',
  'viral_discussion', 'misinformation', 'other'
);
create type escalation_status as enum (
  'open', 'in_progress', 'pending_approval', 'resolved', 'dismissed'
);

create type automation_rule_status as enum ('active', 'inactive', 'draft');

create type actor_type as enum ('user', 'system', 'ai', 'integration');
create type audit_entity_type as enum (
  'organization', 'membership', 'location', 'platform_connection',
  'platform_profile', 'mention', 'mention_analysis', 'response_draft',
  'approval', 'escalation', 'automation_rule'
);

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_updated_at is
  'Trigger function: stamps updated_at on every UPDATE so callers cannot forget.';

-- ---------------------------------------------------------------------------
-- users
--
-- Profile mirror of the auth provider. id equals auth.users.id so RLS can
-- compare against auth.uid() without an extra join. No credentials here.
-- ---------------------------------------------------------------------------

create table public.users (
  id uuid primary key,
  email text not null unique,
  full_name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.users is
  'Profile data for a person. Mirrors auth.users; holds no secrets.';
comment on column public.users.id is
  'Matches auth.users.id. Not generated here — the auth provider owns it.';

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- organizations
-- ---------------------------------------------------------------------------

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) > 0),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  industry text not null,
  website_url text,
  default_timezone text not null default 'UTC',
  default_language text not null default 'en-US',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.organizations is
  'Tenant root. Every business record descends from exactly one organization.';
comment on column public.organizations.slug is
  'Globally unique, URL-safe. Stable once issued because it appears in links.';

create trigger organizations_set_updated_at
  before update on public.organizations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- memberships
-- ---------------------------------------------------------------------------

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id uuid not null references public.users (id) on delete cascade,
  role membership_role not null default 'viewer',
  status membership_status not null default 'invited',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint memberships_unique_user_per_org unique (organization_id, user_id)
);

comment on table public.memberships is
  'Grants a user one role in one organization. A user may hold several memberships.';
comment on column public.memberships.status is
  'Only "active" grants access. RLS ignores invited and suspended rows.';

create index memberships_user_active_idx
  on public.memberships (user_id)
  where status = 'active';
create index memberships_organization_idx
  on public.memberships (organization_id, status);

create trigger memberships_set_updated_at
  before update on public.memberships
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- locations
-- ---------------------------------------------------------------------------

create table public.locations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  slug text not null check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  address_line1 text not null,
  address_line2 text,
  city text not null,
  region text not null,
  postal_code text not null,
  country_code char(2) not null check (country_code ~ '^[A-Z]{2}$'),
  timezone text not null,
  status location_status not null default 'setup',
  -- Nulled rather than cascaded: losing a manager must not delete the location.
  manager_user_id uuid references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locations_unique_slug_per_org unique (organization_id, slug)
);

comment on table public.locations is
  'A physical restaurant. Slugs are unique per organization, not globally.';
comment on column public.locations.manager_user_id is
  'Location manager. Application layer requires an active membership in the same organization.';

create index locations_organization_status_idx
  on public.locations (organization_id, status);
create index locations_manager_idx
  on public.locations (manager_user_id)
  where manager_user_id is not null;

create trigger locations_set_updated_at
  before update on public.locations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- platform_connections
-- ---------------------------------------------------------------------------

create table public.platform_connections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  platform platform not null,
  external_account_id text,
  external_account_name text,
  status platform_connection_status not null default 'pending',
  capabilities jsonb not null default '{}'::jsonb,
  token_expires_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_connections_unique_account
    unique (organization_id, platform, external_account_id)
);

comment on table public.platform_connections is
  'An authorised link to a platform account. Holds no credentials — see platform_connection_secrets.';
comment on column public.platform_connections.capabilities is
  'ConnectorCapabilities object. Drives whether the UI may offer direct publishing.';

create index platform_connections_organization_idx
  on public.platform_connections (organization_id, platform);
create index platform_connections_status_idx
  on public.platform_connections (organization_id, status);

create trigger platform_connections_set_updated_at
  before update on public.platform_connections
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- platform_connection_secrets
--
-- Separate table so tokens are never reachable from a normal user session:
-- migration 20260801000200 grants it no policies at all, which means only the
-- service role can touch it.
-- ---------------------------------------------------------------------------

create table public.platform_connection_secrets (
  platform_connection_id uuid primary key
    references public.platform_connections (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  access_token text,
  refresh_token text,
  scopes text[] not null default '{}',
  rotated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.platform_connection_secrets is
  'OAuth material. Service role only: RLS is enabled with zero policies, so authenticated users see nothing.';

create trigger platform_connection_secrets_set_updated_at
  before update on public.platform_connection_secrets
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- platform_profiles
-- ---------------------------------------------------------------------------

create table public.platform_profiles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  location_id uuid references public.locations (id) on delete set null,
  platform_connection_id uuid not null
    references public.platform_connections (id) on delete cascade,
  external_profile_id text not null,
  external_profile_name text not null,
  profile_url text,
  status platform_profile_status not null default 'pending',
  sync_cursor text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint platform_profiles_unique_external
    unique (platform_connection_id, external_profile_id)
);

comment on table public.platform_profiles is
  'One monitored presence on a platform, usually bound to a location.';
comment on column public.platform_profiles.sync_cursor is
  'Opaque, connector-defined resume point: a page token, high-water mark, or Reddit fullname.';

create index platform_profiles_organization_idx
  on public.platform_profiles (organization_id);
create index platform_profiles_location_idx
  on public.platform_profiles (location_id)
  where location_id is not null;

create trigger platform_profiles_set_updated_at
  before update on public.platform_profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- mentions
-- ---------------------------------------------------------------------------

create table public.mentions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  location_id uuid references public.locations (id) on delete set null,
  platform_connection_id uuid not null
    references public.platform_connections (id) on delete cascade,
  platform_profile_id uuid references public.platform_profiles (id) on delete set null,
  source_type mention_source_type not null,
  external_id text not null,
  external_parent_id text,
  source_url text,
  title text,
  content text not null,
  author_name text,
  author_external_id text,
  rating numeric(2, 1) check (rating is null or (rating >= 0 and rating <= 5)),
  language text,
  published_at timestamptz not null,
  received_at timestamptz not null default now(),
  status mention_status not null default 'new',
  sentiment sentiment not null default 'unknown',
  risk_level risk_level not null default 'low',
  relevance_score numeric(4, 3)
    check (relevance_score is null or (relevance_score >= 0 and relevance_score <= 1)),
  engagement_score numeric(4, 3)
    check (engagement_score is null or (engagement_score >= 0 and engagement_score <= 1)),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Ingest runs at-least-once, so the same review can arrive twice. This is
  -- what makes a re-sync idempotent rather than duplicating the queue.
  constraint mentions_unique_external
    unique (platform_connection_id, source_type, external_id)
);

comment on table public.mentions is
  'The universal mention. Every external source normalises into this shape.';
comment on column public.mentions.raw_payload is
  'Verbatim source response. Preserved so normalisation changes never lose data.';
comment on column public.mentions.received_at is
  'When Lia ingested the mention. Differs from published_at after a backfill.';
comment on constraint mentions_unique_external on public.mentions is
  'Makes re-sync idempotent: a repeated fetch updates rather than duplicates.';

create index mentions_org_published_idx
  on public.mentions (organization_id, published_at desc);
create index mentions_org_status_idx
  on public.mentions (organization_id, status);
create index mentions_org_risk_idx
  on public.mentions (organization_id, risk_level, published_at desc);
create index mentions_org_location_idx
  on public.mentions (organization_id, location_id, published_at desc);
create index mentions_org_source_type_idx
  on public.mentions (organization_id, source_type, published_at desc);

create trigger mentions_set_updated_at
  before update on public.mentions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- mention_analyses
--
-- Append-only history: re-analysing a mention inserts a new row rather than
-- overwriting, so model changes stay auditable. Readers take the latest.
-- ---------------------------------------------------------------------------

create table public.mention_analyses (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  mention_id uuid not null references public.mentions (id) on delete cascade,
  model_provider text not null,
  model_name text not null,
  prompt_version text not null,
  relevance_score numeric(4, 3) not null
    check (relevance_score >= 0 and relevance_score <= 1),
  relevance_explanation text,
  sentiment sentiment not null,
  sentiment_score numeric(4, 3)
    check (sentiment_score is null or (sentiment_score >= -1 and sentiment_score <= 1)),
  risk_level risk_level not null,
  risk_categories escalation_category[] not null default '{}',
  risk_explanation text,
  topics text[] not null default '{}',
  facts_needing_verification text[] not null default '{}',
  recommended_action recommended_action not null,
  recommendation_explanation text,
  analyzed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

comment on table public.mention_analyses is
  'Model output for a mention. Append-only: re-analysis inserts, never updates.';
comment on column public.mention_analyses.facts_needing_verification is
  'Claims a human must check before Lia repeats or contradicts them.';

create index mention_analyses_mention_idx
  on public.mention_analyses (mention_id, analyzed_at desc);
create index mention_analyses_organization_idx
  on public.mention_analyses (organization_id);

-- ---------------------------------------------------------------------------
-- response_drafts
-- ---------------------------------------------------------------------------

create table public.response_drafts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  mention_id uuid not null references public.mentions (id) on delete cascade,
  response_type response_type not null,
  draft_text text not null,
  final_text text,
  status response_draft_status not null default 'draft',
  generated_by generated_by not null default 'ai',
  generation_provider text,
  generation_model text,
  prompt_version text,
  brand_voice_version text,
  policy_version text,
  assigned_user_id uuid references public.users (id) on delete set null,
  approved_by_user_id uuid references public.users (id) on delete set null,
  approved_at timestamptz,
  published_at timestamptz,
  external_response_id text,
  publication_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A published response must record who signed it off.
  constraint response_drafts_published_requires_approval
    check (status <> 'published' or approved_by_user_id is not null)
);

comment on table public.response_drafts is
  'A response from first draft to published. draft_text is the model output; final_text is what a human settled on.';
comment on constraint response_drafts_published_requires_approval on public.response_drafts is
  'Nothing reaches published without a recorded approver.';

create index response_drafts_org_status_idx
  on public.response_drafts (organization_id, status);
create index response_drafts_mention_idx
  on public.response_drafts (mention_id, created_at desc);
create index response_drafts_assignee_idx
  on public.response_drafts (assigned_user_id)
  where assigned_user_id is not null;

create trigger response_drafts_set_updated_at
  before update on public.response_drafts
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- approvals
-- ---------------------------------------------------------------------------

create table public.approvals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  response_draft_id uuid not null
    references public.response_drafts (id) on delete cascade,
  requested_by_user_id uuid references public.users (id) on delete set null,
  assigned_to_user_id uuid references public.users (id) on delete set null,
  status approval_status not null default 'pending',
  decision_note text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approvals_decided_has_timestamp
    check (status in ('pending', 'canceled') or decided_at is not null)
);

comment on table public.approvals is
  'The approval request: who was asked, by whom, and what they decided. The outcome also lands on the draft.';

create index approvals_org_status_idx
  on public.approvals (organization_id, status);
create index approvals_draft_idx
  on public.approvals (response_draft_id, created_at desc);

create trigger approvals_set_updated_at
  before update on public.approvals
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- escalations
-- ---------------------------------------------------------------------------

create table public.escalations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  mention_id uuid not null references public.mentions (id) on delete cascade,
  category escalation_category not null,
  severity risk_level not null,
  status escalation_status not null default 'open',
  title text not null check (length(trim(title)) > 0),
  summary text,
  assigned_user_id uuid references public.users (id) on delete set null,
  due_at timestamptz,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- A case that closes with no explanation looks handled when it is not.
  constraint escalations_resolved_requires_note
    check (status <> 'resolved' or (resolved_at is not null and resolution_note is not null))
);

comment on table public.escalations is
  'A sensitive issue lifted out of the queue and given an owner. Always originates from a mention.';
comment on constraint escalations_resolved_requires_note on public.escalations is
  'Resolving requires both a timestamp and a written resolution.';

create index escalations_org_status_idx
  on public.escalations (organization_id, status, severity);
create index escalations_org_due_idx
  on public.escalations (organization_id, due_at)
  where status not in ('resolved', 'dismissed');
create index escalations_mention_idx on public.escalations (mention_id);

create trigger escalations_set_updated_at
  before update on public.escalations
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- automation_rules
-- ---------------------------------------------------------------------------

create table public.automation_rules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  name text not null check (length(trim(name)) > 0),
  description text,
  status automation_rule_status not null default 'draft',
  priority integer not null default 100 check (priority >= 0 and priority <= 1000),
  conditions jsonb not null default '[]'::jsonb,
  actions jsonb not null default '[]'::jsonb,
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint automation_rules_conditions_is_array
    check (jsonb_typeof(conditions) = 'array'),
  constraint automation_rules_actions_is_array
    check (jsonb_typeof(actions) = 'array'),
  constraint automation_rules_unique_name_per_org unique (organization_id, name)
);

comment on table public.automation_rules is
  'Declarative rules. conditions and actions are validated against Zod schemas in src/domain/entities/automation.ts before write.';
comment on column public.automation_rules.priority is
  'Lower runs first. Ties break on created_at.';

create index automation_rules_org_status_idx
  on public.automation_rules (organization_id, status, priority);

create trigger automation_rules_set_updated_at
  before update on public.automation_rules
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- audit_events
--
-- Append-only. No updated_at, and migration 20260801000200 revokes UPDATE and
-- DELETE from the authenticated role.
-- ---------------------------------------------------------------------------

create table public.audit_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  actor_user_id uuid references public.users (id) on delete set null,
  actor_type actor_type not null default 'user',
  event_type text not null,
  entity_type audit_entity_type not null,
  entity_id uuid not null,
  previous_state jsonb,
  new_state jsonb,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  -- Closed list rather than free text: a typo in an audit trail is worse than
  -- a failed insert. Mirrors AUDIT_EVENT_TYPES in src/domain/enums.ts.
  constraint audit_events_known_event_type check (
    event_type in (
      'mention.status_changed',
      'response.assigned',
      'response.approved',
      'response.rejected',
      'escalation.assigned',
      'escalation.status_changed',
      'automation_rule.enabled',
      'automation_rule.disabled',
      'location.manager_changed'
    )
  )
);

comment on table public.audit_events is
  'Append-only trail of meaningful state changes. Insert and select only for application users.';
comment on column public.audit_events.event_type is
  'Dotted event name, e.g. mention.status_changed. Constrained to the closed list in src/domain/enums.ts.';
comment on column public.audit_events.previous_state is
  'Only the fields that changed, before the write. Null for creation events.';

create index audit_events_org_occurred_idx
  on public.audit_events (organization_id, occurred_at desc);
create index audit_events_entity_idx
  on public.audit_events (organization_id, entity_type, entity_id, occurred_at desc);
create index audit_events_actor_idx
  on public.audit_events (organization_id, actor_user_id, occurred_at desc);
